/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        final GUI gui = new GUI(10, () -> {System.exit(0);});
        gui.showGUI();

    }
}
